LOAN_STATUS_ACTIVE = "Active"
LOAN_STATUS_INACTIVE = "Inactive"
LOAN_STATUS_NONE = "NONE"

REQUEST_LOAN_APPROVED = "Approved" 
REQUEST_LOAN_DECLINED = "Declined" 
REQUEST_LOAN_UNDECIDED = "Undecided" 

REQUEST_LOAN_INVALID = "Invalid"